name: resume_maker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core:
  connectivity_plus: ^3.0.3
  cached_network_image: ^3.2.3
  get_it: ^7.2.0
  multiselect: ^0.1.0
  image_picker: ^0.8.7
  image_cropper: ^3.0.1
  cloud_firestore: ^4.4.4
  firebase_storage: ^11.0.15
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

