// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqp8XBYPapb0ftvJC9jWJTxKv3-_oZyYo',
    appId: '1:736336828016:web:7e07cab1b80c3682d786b5',
    messagingSenderId: '736336828016',
    projectId: 'resumemaker-3624b',
    authDomain: 'resumemaker-3624b.firebaseapp.com',
    storageBucket: 'resumemaker-3624b.appspot.com',
    measurementId: 'G-Z5DKM0Q6HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKsQskUHSMc_5j1eJy16CJ7D0o-J14g4',
    appId: '1:736336828016:android:b9d08693369e91afd786b5',
    messagingSenderId: '736336828016',
    projectId: 'resumemaker-3624b',
    storageBucket: 'resumemaker-3624b.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZVUPuPmH2mKv-t25wVX_KL-3H9K3MbkA',
    appId: '1:736336828016:ios:51d312ae8fe35099d786b5',
    messagingSenderId: '736336828016',
    projectId: 'resumemaker-3624b',
    storageBucket: 'resumemaker-3624b.appspot.com',
    iosClientId: '736336828016-ju7s1aehmplckf76hujvo9b8imq29va4.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeMaker',
  );
}
